version: "3.9"

services:
  ballance_frontend:
    image: registry.gitlab.com/ballance.ru/frontend:main
    restart: unless-stopped
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=ballance.pro
      - VIRTUAL_PORT=80

networks:
  default:
    external:
      name: nginx-proxy